const mentors = [
  {
    name: 'Dr. Priya Sharma',
    role: 'Senior Research Scientist',
    company: 'IISc Bangalore',
    expertise: ['Research', 'PhD Guidance', 'Biology', 'Biochemistry'],
    bio: 'PhD in Biochemistry from IISc with 12 years of research experience. Passionate about guiding students into research careers.',
    forTypes: ['pg', 'ug'],
    email: 'mentor@careercompass.in',
    linkedin: 'https://linkedin.com',
    rating: 4.9,
    sessions: 245,
  },
  {
    name: 'Arjun Mehta',
    role: 'Engineering Manager',
    company: 'Google India',
    expertise: ['Software Engineering', 'DSA', 'System Design', 'Career Switch'],
    bio: 'B.Tech from IIT Bombay, 10 years at Google. Helps CS students crack FAANG interviews and navigate tech careers.',
    forTypes: ['ug', 'professional'],
    email: 'mentor@careercompass.in',
    linkedin: 'https://linkedin.com',
    rating: 4.8,
    sessions: 320,
  },
  {
    name: 'Meera Iyer',
    role: 'CA & Finance Expert',
    company: 'Deloitte India',
    expertise: ['CA/CS Coaching', 'Commerce', 'Finance', 'Investment Banking'],
    bio: 'Chartered Accountant with 8 years in Big 4 consulting. Guides 12th Commerce students and working finance professionals.',
    forTypes: ['twelfth', 'ug', 'professional'],
    email: 'mentor@careercompass.in',
    linkedin: 'https://linkedin.com',
    rating: 4.7,
    sessions: 189,
  },
  {
    name: 'Rohan Kapoor',
    role: 'Entrepreneur & Startup Mentor',
    company: 'StartupIndia',
    expertise: ['Entrepreneurship', 'MBA', 'Business Strategy', 'Fundraising'],
    bio: 'Founded 2 startups, IIM Ahmedabad alumnus. Mentors aspiring entrepreneurs and MBA aspirants.',
    forTypes: ['pg', 'professional', 'ug'],
    email: 'mentor@careercompass.in',
    linkedin: 'https://linkedin.com',
    rating: 4.6,
    sessions: 152,
  },
  {
    name: 'Dr. Ananya Das',
    role: 'MBBS Counsellor & Doctor',
    company: 'AIIMS New Delhi',
    expertise: ['NEET Prep', 'Medical Careers', 'MBBS Abroad', 'Specialization Selection'],
    bio: 'MBBS + MD from AIIMS. Helps students navigate NEET, medical college selection, and specialty choices.',
    forTypes: ['twelfth', 'ug'],
    email: 'mentor@careercompass.in',
    linkedin: 'https://linkedin.com',
    rating: 4.9,
    sessions: 278,
  },
  {
    name: 'Sunita Krishnan',
    role: 'Career Counsellor & Psychologist',
    company: 'CareerPath Foundation',
    expertise: ['Stream Selection', 'Aptitude Assessment', 'Career Planning', 'Counselling'],
    bio: 'Certified career counsellor helping 10th and 12th students discover their true calling through psychometric assessments.',
    forTypes: ['tenth', 'twelfth'],
    email: 'mentor@careercompass.in',
    linkedin: 'https://linkedin.com',
    rating: 4.8,
    sessions: 410,
  },
  {
    name: 'Vikram Nair',
    role: 'Data Science Lead',
    company: 'Flipkart',
    expertise: ['Data Science', 'Machine Learning', 'Python', 'Career Transition'],
    bio: 'Mechanical engineer turned data scientist. Helps professionals switch to data science roles with a proven roadmap.',
    forTypes: ['professional', 'ug'],
    email: 'mentor@careercompass.in',
    linkedin: 'https://linkedin.com',
    rating: 4.7,
    sessions: 198,
  },
  {
    name: 'Prof. Lakshmi Rao',
    role: 'Professor & Abroad Study Expert',
    company: 'MIT (Visiting)',
    expertise: ['GRE', 'GMAT', 'SOP Writing', 'Abroad Admissions', 'Scholarships'],
    bio: 'Helped 500+ students get into top global universities. Expert in GRE prep and scholarship applications.',
    forTypes: ['pg', 'professional'],
    email: 'mentor@careercompass.in',
    linkedin: 'https://linkedin.com',
    rating: 5.0,
    sessions: 512,
  },
];

module.exports = mentors;
