const scholarships = [
  {
    name: 'National Merit Scholarship',
    provider: 'Ministry of Education, India',
    amount: '₹12,000/year',
    level: 'twelfth',
    eligibility: 'Scored above 60% in 10th board exams. Family income below ₹1.5 LPA.',
    deadline: '31 October 2025',
    link: 'https://scholarships.gov.in',
    category: 'Merit',
    state: 'All India',
  },
  {
    name: 'Post Matric Scholarship (SC/ST)',
    provider: 'Ministry of Social Justice',
    amount: '₹23,000/year',
    level: 'twelfth',
    eligibility: 'SC/ST students pursuing 11th-12th. Family income below ₹2.5 LPA.',
    deadline: '31 December 2025',
    link: 'https://scholarships.gov.in',
    category: 'Category',
    state: 'All India',
  },
  {
    name: 'INSPIRE Scholarship',
    provider: 'Department of Science & Technology',
    amount: '₹80,000/year',
    level: 'ug',
    eligibility: 'Top 1% in 12th board exams pursuing BSc/Integrated MSc in natural sciences.',
    deadline: '30 November 2025',
    link: 'https://online-inspire.gov.in',
    category: 'Merit',
    state: 'All India',
  },
  {
    name: 'Kishore Vaigyanik Protsahan Yojana (KVPY)',
    provider: 'Indian Institute of Science',
    amount: '₹5,000–7,000/month',
    level: 'ug',
    eligibility: 'Students pursuing BSc/BS/B.Stat/B.Math/Int.M.Sc in Science stream.',
    deadline: 'August 2025',
    link: 'https://kvpy.iisc.ernet.in',
    category: 'Research',
    state: 'All India',
  },
  {
    name: 'Aicte Pragati Scholarship (Girls)',
    provider: 'AICTE',
    amount: '₹50,000/year',
    level: 'ug',
    eligibility: 'Girl students in AICTE approved institutions. Max 2 per family. Income < ₹8 LPA.',
    deadline: '31 October 2025',
    link: 'https://www.aicte-pragati-saksham-gov.in',
    category: 'Gender',
    state: 'All India',
  },
  {
    name: 'GATE Fellowship',
    provider: 'Ministry of Human Resource Development',
    amount: '₹12,400/month',
    level: 'pg',
    eligibility: 'Valid GATE score, pursuing M.Tech/ME in AICTE-approved institutions.',
    deadline: 'July 2025',
    link: 'https://mhrd.gov.in',
    category: 'Merit',
    state: 'All India',
  },
  {
    name: 'Commonwealth Scholarship (UK)',
    provider: 'Commonwealth Scholarship Commission',
    amount: 'Full funding (tuition + living)',
    level: 'pg',
    eligibility: 'Indian citizens, first PG degree, below 40 years, strong academic record.',
    deadline: '15 December 2025',
    link: 'https://cscuk.fcdo.gov.uk',
    category: 'International',
    state: 'All India',
  },
  {
    name: 'Tata Social Enterprise Scholarship',
    provider: 'Tata Institute of Social Sciences',
    amount: '₹2,00,000/year',
    level: 'pg',
    eligibility: 'Postgraduate students in social enterprise / development management programs.',
    deadline: '28 February 2026',
    link: 'https://www.tiss.edu',
    category: 'Social',
    state: 'All India',
  },
  {
    name: 'UGC JRF Fellowship',
    provider: 'University Grants Commission',
    amount: '₹31,000/month',
    level: 'pg',
    eligibility: 'NET qualified candidates for PhD research in any discipline.',
    deadline: 'Continuous',
    link: 'https://ugcnetonline.in',
    category: 'Research',
    state: 'All India',
  },
  {
    name: 'Fulbright-Nehru Master\'s Fellowship',
    provider: 'U.S.-India Educational Foundation',
    amount: 'Full funding (USA)',
    level: 'professional',
    eligibility: 'Working professionals with 3+ years experience. Strong leadership profile.',
    deadline: '15 July 2025',
    link: 'https://www.usief.org.in',
    category: 'International',
    state: 'All India',
  },
  {
    name: 'Dhirubhai Ambani Scholarship',
    provider: 'Reliance Foundation',
    amount: '₹2,00,000/year',
    level: 'ug',
    eligibility: 'Top BTech/MBA students from Tier-2/3 cities. Based on merit + need.',
    deadline: '30 September 2025',
    link: 'https://reliancefoundation.org',
    category: 'Merit',
    state: 'All India',
  },
  {
    name: 'Vidyasaarathi Scholarship',
    provider: 'NSDL e-Governance',
    amount: 'Up to ₹50,000',
    level: 'all',
    eligibility: 'Students from economically weaker sections. All levels considered.',
    deadline: '31 March 2026',
    link: 'https://www.vidyasaarathi.co.in',
    category: 'Need-based',
    state: 'All India',
  },
];

module.exports = scholarships;
